### ISSUE TITLE
Cut crates.io release

### ISSUE THREAD

**Issue by ogghead** [leptos-rs/leptos_wasi#8]
Hi folks, getting back to this and I noticed that the Leptos 0.7 integration for leptos-spin is having problems after #4 where versions of Leptos became mismatched. I would like to propose cutting an rc1 version of this crate so that templates can rely on that version until 0.7 full release. I am happy to complete this work if it makes sense to folks, but wanted to start a discussion either way! This would involve:

- [x] Creating a PR to lock all versions of dependencies -- mostly by using "rc1" versions of Leptos crates but also by locking git crate versions to specific commits when necessary
- [ ]  Tagging this version and publishing to crates.io

Curious to hear thoughts on this!

**Comment by raskyld** [comment]
We could but I think you made one change that is in `main` on Leptos which we rely upon (I think re-exporting any_spawner or something like that, sorry I don't remember exactly)

**Comment by benwis** [comment]
I think releasing something tied to rc1 makes sense, assuming it has what you need. I can always do an rc2 if it doesnty

**Comment by ogghead** [comment]
> We could but I think you made one change that is in `main` on Leptos which we rely upon (I think re-exporting any_spawner or something like that, sorry I don't remember exactly)

> I think releasing something tied to rc1 makes sense, assuming it has what you need. I can always do an rc2 if it doesnt

Good points! https://github.com/leptos-rs/leptos/pull/3195 does add the flagged functionality that @raskyld created in any_spawner as a re-export in Leptos, which makes it easier for templates to pull in. For _fully_ reproducible builds, having that in rc2 would be wonderful @benwis! This crate could also use a pinned commit of any_spawner to achieve reproducibility using rc1 too though

**Comment by ogghead** [comment]
Tentatively created an rc1 locked version PR

**Comment by benwis** [comment]
We've released leptos_wasi v0.1.1 on crates.io!
